Repository PandasWS/Pandas, pull requests merged in 2020-08, with the labels that each got.

#301 处理 Windows 10 的 UTF8 编码选项带来的中文乱码问题
  conf/msg_conf/translation_cn.yml
  conf/msg_conf/translation_tw.yml
  src/common/core.cpp
  src/common/translate.cpp
  src/common/utf8.cpp
  src/common/utf8.hpp
  src/config/pandas.hpp
  src/map/map-server.vcxproj
  tools/python/pyhelp_extracter.py
Labels: type:bug

#303 修正部分装备无法在背包和装备面板中显示的问题 (感谢"喵了个咪"反馈)
  src/map/clif.cpp
Labels: type:bug

#305 修正点击副本销毁按钮可能会导致地图服务器无响应的问题 (感谢"喵了个咪"反馈)
  src/map/instance.cpp
Labels: type:bug

#308 修正一些已知会导致崩溃的情况 (感谢"张大坏"反馈)
  README.md
  rAthena.ruleset
  src/char/char-server.vcxproj
  src/char/char_clif.cpp
  src/char/char_logif.cpp
  src/common/nullpo.hpp
  src/config/pandas.hpp
  src/login/login-server.vcxproj
  src/map/clif.cpp
  src/map/itemdb.cpp
  src/map/map-server.vcxproj
  src/map/npc.cpp
  src/map/pc.cpp
  src/map/script.cpp
  src/map/skill.cpp
  src/map/status.cpp
  src/tool/csv2yaml.vcxproj
  src/tool/mapcache.vcxproj
  tools/python/pyhelp_atcmd.py
  tools/python/pyhelp_battlecfg.py
  tools/python/pyhelp_compile.py
  tools/python/pyhelp_extracter.py
  tools/python/pyhelp_mapflag.py
  tools/python/pyhelp_npcevent.py
  tools/python/pyhelp_publish.py
  tools/python/pyhelp_scriptcmd.py
  tools/python/pyhelp_src2utf8.py
  tools/python/pyhelp_symstore.py
  tools/python/pyhelp_translate.py
  tools/python/pyhelp_versions.py
Labels: type:bug

#307 汉化 部分服务器消息文件和帮助文档
  conf/atcommands.yml
  conf/charhelp.txt
  conf/groups.conf
  conf/msg_conf/char_msg_chs.conf
  conf/msg_conf/login_msg_chs.conf
  conf/msg_conf/map_msg_chs.conf
Labels: type:experience

#309 使服务端能够读取 SSO 方式登录的用户本地 MAC 地址
  doc/pandas_script_commands.txt
  src/char/char.hpp
  src/char/char_clif.cpp
  src/char/char_logif.cpp
  src/char/char_mapif.cpp
  src/common/iconv.hpp
  src/common/mmo.hpp
  src/common/socket.cpp
  src/common/socket.hpp
  src/config/pandas.hpp
  src/login/account.hpp
  src/login/login.cpp
  src/login/login.hpp
  src/login/loginchrif.cpp
  src/login/loginclif.cpp
  src/map/chrif.cpp
  src/map/packets.hpp
  src/map/packets_struct.hpp
  src/map/script.cpp
Labels: type:enhancement

#310 对数据库升级脚本进行一些重新整理, 以便适应未来
  sql-files/composer/logs/upgrade_from_rAthenaCN-1.8.0_logs.sql
  sql-files/composer/logs/upgrade_to_1.0.7_logs.sql
  sql-files/composer/main/upgrade_from_rAthenaCN-1.8.0_main.sql
  sql-files/composer/main/upgrade_from_rAthenaCN-1.8.0_main_use_sql_db.sql
  sql-files/composer/main/upgrade_to_1.0.3_main.sql
  sql-files/composer/main/upgrade_to_1.0.5_main.sql
  sql-files/composer/main/upgrade_to_1.0.6_main.sql
  sql-files/composer/main/upgrade_to_1.0.7_main.sql
  sql-files/composer/main/upgrade_to_1.0.7_main_use_sql_db.sql
Labels: type:bug, type:enhancement

#311 使用 pipenv 对辅助脚本的依赖库进行管理维护 (合理性和使用难度同时提高)
  tools/python/Pipfile
  tools/python/Pipfile.lock
  tools/python/README.md
  tools/python/documentations/images/python_installer/1.png
  tools/python/documentations/images/python_installer/2.png
  tools/python/documentations/images/python_installer/3.png
  tools/python/requirements.txt
Labels: type:enhancement

#312 修正多层脚本堆栈备份恢复时的一处错误 (感谢"张大坏"反馈)
  conf/msg_conf/translation_cn.yml
  conf/msg_conf/translation_tw.yml
  src/map/script.cpp
Labels: type:bug

#313 修正当 block_free 存在重复指针时的无效指针的问题 (感谢"喵了个咪"反馈)
  src/config/pandas.hpp
  src/map/map.cpp
Labels: type:bug

#315 实现 nohomun 地图标记, 用于禁止在指定地图召唤人工生命体
  conf/msg_conf/map_msg.conf
  conf/msg_conf/map_msg_chs.conf
  conf/msg_conf/map_msg_cht.conf
  doc/pandas_mapflags.txt
  src/config/pandas.hpp
  src/map/clif.cpp
  src/map/homunculus.cpp
  src/map/map.cpp
Labels: type:enhancement

#316 实现 nomerc 地图标记, 用于禁止在指定地图召唤佣兵
  conf/msg_conf/map_msg.conf
  conf/msg_conf/map_msg_chs.conf
  conf/msg_conf/map_msg_cht.conf
  conf/msg_conf/translation_cn.yml
  conf/msg_conf/translation_tw.yml
  doc/pandas_mapflags.txt
  src/config/pandas.hpp
  src/map/clif.cpp
  src/map/map.cpp
  src/map/mercenary.cpp
Labels: type:enhancement

#317 实现 noskill2 地图标记, 用于限制指定类型的单位在地图上使用技能
  doc/pandas_mapflags.txt
  src/config/pandas.hpp
  src/map/atcommand.cpp
  src/map/clif.cpp
  src/map/elemental.cpp
  src/map/map.cpp
  src/map/map.hpp
  src/map/mob.cpp
  src/map/npc.cpp
  src/map/pet.cpp
  src/map/script_constants.hpp
  src/map/skill.cpp
  src/map/unit.cpp
Labels: type:enhancement
