Repository PandasWS/Pandas, pull requests merged in 2021-12, with the labels that each got.

#461 修正光环机制导致 cloakonnpc 无效的问题 (感谢 "ghost" 反馈)
  src/map/clif.cpp
Labels: 分类:程序缺陷, 组件:核心, 模式:全包括, 优先级:P2普通, MIP:S5已测试

#412 实现 bSkillNoRequire 调整器, 用于解除 sk 技能中由 n 指定的前置施法条件限制
  doc/pandas_bonus.txt
  src/config/pandas.hpp
  src/map/map.hpp
  src/map/pc.cpp
  src/map/pc.hpp
  src/map/script.cpp
  src/map/script_constants.hpp
  src/map/skill.cpp
  src/map/skill.hpp
  src/map/status.cpp
Labels: 分类:功能需求, MIP:S6已上线, 优先级:P2普通

#423 攻击拥有 sc 状态的目标时, 使用 bf 攻击有 r/100% 的概率使伤害增加 n 或 n%
  doc/pandas_bonus.txt
  src/config/pandas.hpp
  src/map/battle.cpp
  src/map/map.hpp
  src/map/pc.cpp
  src/map/pc.hpp
  src/map/script_constants.hpp
  src/map/skill.cpp
  src/map/status.cpp
Labels: 分类:功能需求, MIP:S6已上线, 优先级:P2普通

#435 实现 OnPCMerCallExpress 实时事件, 当玩家成功召唤出佣兵时触发 [HongShin]
  .github/workflows/build-and-test.yml
  .github/workflows/codeql-analysis.yml
  doc/pandas_events.txt
  src/config/pandas.hpp
  src/map/mercenary.cpp
  src/map/npc.cpp
  src/map/npc.hpp
  src/map/script.cpp
  src/map/script.hpp
  src/map/script_constants.hpp
Labels: 分类:功能需求, 优先级:P2普通

#434 实现 OnPCMerLeaveExpress 实时事件, 当佣兵离开玩家时触发 [HongShin]
  doc/pandas_events.txt
  src/config/pandas.hpp
  src/map/mercenary.cpp
  src/map/npc.cpp
  src/map/npc.hpp
  src/map/script.cpp
  src/map/script.hpp
  src/map/script_constants.hpp
Labels: 分类:功能需求, 优先级:P2普通

#460 实现 OnPCDropItemFilter 过滤器, 当玩家准备丢弃或掉落道具时触发 [人鱼姬的思念]
  doc/pandas_events.txt
  src/config/pandas.hpp
  src/map/npc.cpp
  src/map/npc.hpp
  src/map/pc.cpp
  src/map/script.cpp
  src/map/script.hpp
  src/map/script_constants.hpp
Labels: 分类:功能需求, 优先级:P2普通, MIP:S5已测试

#463 实现 boss_monster 脚本指令, 召唤魔物并使之能被 BOSS 雷达探测 [人鱼姬的思念]
  doc/pandas_script_commands.txt
  src/config/pandas.hpp
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/map.cpp
  src/map/map.hpp
  src/map/mob.cpp
  src/map/mob.hpp
  src/map/script.cpp
  src/map/status.cpp
Labels: 分类:功能需求, MIP:S6已上线, 优先级:P2普通

#452 实现 sleep3 脚本指令, 用于休眠一段时间再执行后续脚本 (与 sleep2 类似但忽略报错) [人鱼姬的思念]
  doc/pandas_script_commands.txt
  src/config/pandas.hpp
  src/map/script.cpp
Labels: 分类:功能需求, 优先级:P2普通, MIP:S5已测试

#422 [Bonus]bf攻击对r种族及c类别魔物的最终伤害全段修正
  doc/pandas_bonus.txt
  src/config/pandas.hpp
  src/map/battle.cpp
  src/map/map.hpp
  src/map/pc.cpp
  src/map/pc.hpp
  src/map/script_constants.hpp
  src/map/skill.cpp
  src/map/status.cpp
Labels: 分类:功能需求, 优先级:P2普通, MIP:S5已测试

#428 修正部分场景下 detachrid 之后与其他 NPC 对话, 会导致其他 NPC 消失的问题
  src/config/pandas.hpp
  src/map/script.cpp
Labels: 分类:程序缺陷, MIP:S6已上线, 组件:核心, 优先级:P2普通

#466 使疾风缓存支持新的两个数据库 (缓存后 DEBUG 模式启动速度缩减 10 秒)
  src/common/serialize.hpp
  src/config/pandas.hpp
  src/map/itemdb.hpp
  src/map/mob.hpp
  src/map/pc.cpp
  src/map/pc.hpp
  src/map/quest.hpp
  src/map/skill.hpp
Labels: 分类:功能需求, 优先级:P2普通, MIP:S5已测试

#468 紧急修复 cloakonnpc 指令失效的问题, 优化多处光环系统的细节 (感谢 "306789" 反馈)
  src/config/pandas.hpp
  src/map/aura.cpp
  src/map/aura.hpp
  src/map/clif.cpp
  src/map/npc.cpp
  src/map/status.cpp
  src/map/status.hpp
Labels: 分类:程序缺陷, 优先级:P1较高, 组件:核心, 模式:全包括, MIP:S5已测试
