Repository PandasWS/Pandas, pull requests merged in 2021-06, with the labels that each got.

#372 实装 20181031 及更新的客户端中的背包扩容机制
  conf/msg_conf/translation_cn.yml
  conf/msg_conf/translation_tw.yml
  doc/pandas_script_commands.txt
  npc/features/inventory_expansion.txt
  npc/pre-re/scripts_main.conf
  npc/re/scripts_main.conf
  npc/scripts_features.conf
  sql-files/composer/main/upgrade_to_1.1.2_main.sql
  sql-files/main.sql
  src/char/char.cpp
  src/char/char.hpp
  src/char/int_storage.cpp
  src/common/mmo.hpp
  src/config/pandas.hpp
  src/login/loginclif.cpp
  src/map/atcommand.cpp
  src/map/chrif.cpp
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/clif_packetdb.hpp
  src/map/intif.cpp
  src/map/itemamulet.cpp
  src/map/mail.cpp
  src/map/npc.cpp
  src/map/pc.cpp
  src/map/pc.hpp
  src/map/pet.cpp
  src/map/script.cpp
  src/map/script_constants.hpp
  src/map/skill.cpp
  src/map/status.cpp
  src/map/storage.cpp
  src/map/trade.cpp
Labels: type:enhancement

#371 調整繁體中文物品名稱對照表
  tools/python/db/zh-tw/itemname.txt
Labels: type:experience

#373 修正静态分析警告, 实现格式化占位符检查脚本
  .lgtm.yml
  3rdparty/breakpad/projects/libraries/crash_common.vcxproj
  3rdparty/breakpad/projects/libraries/crash_generation_client.vcxproj
  3rdparty/breakpad/projects/libraries/crash_generation_server.vcxproj
  3rdparty/breakpad/projects/libraries/crash_report_sender.vcxproj
  3rdparty/breakpad/projects/libraries/exception_handler.vcxproj
  conf/msg_conf/map_msg_chs.conf
  conf/msg_conf/map_msg_cht.conf
  conf/msg_conf/translation_cn.yml
  conf/msg_conf/translation_tw.yml
  src/char/char.cpp
  src/char/char_cnslif.cpp
  src/char/char_logif.cpp
  src/char/char_mapif.cpp
  src/char/int_auction.cpp
  src/char/int_clan.cpp
  src/char/int_guild.cpp
  src/char/int_mail.cpp
  src/char/int_party.cpp
  src/char/inter.cpp
  src/common/ers.cpp
  src/common/grfio.cpp
  src/common/performance.cpp
  src/common/socket.cpp
  src/common/sql.cpp
  src/common/utils.cpp
  src/config/pandas.hpp
  src/login/login.cpp
  src/login/loginchrif.cpp
  src/login/logincnslif.cpp
  src/map/mob.cpp
  src/map/npc.cpp
  src/map/pc.cpp
  src/map/script.cpp
  src/map/skill.cpp
  src/map/status.cpp
  tools/python/dawn_fmtargs.py
Labels: type:enhancement, type:experience

#374 丰富编译、打包、签名存储环节的可配置项, 以便进行多项目管理
  tools/python/.config.env.sample
  tools/python/dawn_compile.py
  tools/python/dawn_publish.py
  tools/python/dawn_symstore.py
  tools/python/libs/Common.py
Labels: type:enhancement, type:experience
