Repository PandasWS/Pandas, pull requests merged in 2021-07, with the labels that each got.

#375 修正疾风引擎导致部分战斗配置选项无效的问题
  src/common/database.cpp
  src/common/database.hpp
  src/map/itemdb.hpp
  src/map/mob.cpp
  src/map/mob.hpp
  src/map/quest.hpp
  src/map/skill.cpp
  src/map/skill.hpp
  src/tool/yaml.hpp
Labels: type:bug

#376 修正邮件拥有多个道具附件时, 背包槽位的计算错误
  src/config/pandas.hpp
  src/map/mail.cpp
Labels: type:bug

#377 解决复兴后卡片修正被应用了两次的问题
  src/config/pandas.hpp
  src/map/battle.cpp
Labels: type:bug

#379 调整 item_properties.yml 以匹配正确的 YAML 配置风格
  db/import-tmpl/item_properties.yml
  db/item_properties.yml
  src/config/pandas.hpp
  src/map/clif.cpp
  src/map/itemamulet.cpp
  src/map/itemdb.cpp
  src/map/itemdb.hpp
  src/map/itemprops.cpp
  src/map/itemprops.hpp
  src/map/mob.cpp
  src/map/pc.cpp
  src/map/script.cpp
  src/map/skill.cpp
Labels: type:bug, type:enhancement, type:experience

#380 使用更安全可靠的方式来更新定时器指向的游戏单位编号
  src/common/timer.cpp
  src/common/timer.hpp
  src/map/map.cpp
Labels: type:bug

#382 实现 OnMobDropItemExpress 实时事件, 当魔物即将掉落道具时触发
  db/import-tmpl/item_properties.yml
  db/item_properties.yml
  doc/pandas_events.txt
  src/config/pandas.hpp
  src/map/itemprops.cpp
  src/map/itemprops.hpp
  src/map/mob.cpp
  src/map/npc.cpp
  src/map/npc.hpp
  src/map/script.cpp
  src/map/script.hpp
  src/map/script_constants.hpp
Labels: type:enhancement

#384 修正逐影在“抄袭/复制”技能后角色服务器可能会丢失逐影全部技能的问题
  src/char/char.cpp
  src/config/pandas.hpp
Labels: type:bug

#385 [擴充] announce 使用bc_name，雙擊公告可將發話者ID添加至密語欄
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/script.cpp
  src/map/script_constants.hpp
Labels: type:enhancement

#387 修正 script_instancegetid 中的一处空指针崩溃 (感谢 "VanillaIRV" 反馈)
  src/map/script.cpp
Labels: type:bug

#389 调整缓存的过期策略, 改变结构体大小将强制缓存过期
  src/common/database.cpp
  src/common/database.hpp
  src/common/serialize.hpp
  src/map/itemdb.hpp
  src/map/mob.hpp
  src/map/quest.hpp
  src/map/skill.hpp
Labels: type:enhancement, type:experience

#388 强化邮件系统的参数校验和空指针判断, 避免恶意构造封包导致地图服务器崩溃
  src/map/clif.cpp
  src/map/mail.cpp
Labels: type:bug
