Repository PandasWS/Pandas, pull requests merged in 2022-05, with the labels that each got.

#510 实现 OnPCClickTombFilter 触发器事件, 当玩家点击魔物墓碑时触发 [人鱼姬的思念]
  doc/pandas_events.txt
  src/common/timer.cpp
  src/common/timer.hpp
  src/config/pandas.hpp
  src/map/mob.cpp
  src/map/mob.hpp
  src/map/npc.cpp
  src/map/npc.hpp
  src/map/script.cpp
  src/map/script.hpp
  src/map/script_constants.hpp
Labels: 分类:功能需求, 优先级:P2普通, MIP:S5已测试

#511 当玩家聊天触发实时事件 [人鱼姬的思念]
  doc/pandas_events.txt
  src/config/pandas.hpp
  src/map/clif.cpp
  src/map/npc.cpp
  src/map/npc.hpp
  src/map/script.cpp
  src/map/script.hpp
  src/map/script_constants.hpp
Labels: 分类:功能需求, 优先级:P2普通, MIP:S5已测试

#526 使 getunitdata / setunitdata 可以读取或设置魔物的经验值
  conf/msg_conf/map_msg.conf
  conf/msg_conf/map_msg_chs.conf
  conf/msg_conf/map_msg_cht.conf
  doc/pandas_script_commands.txt
  src/config/pandas.hpp
  src/map/mob.cpp
  src/map/mob.hpp
  src/map/pc.cpp
  src/map/script.cpp
  src/map/script.hpp
  src/map/script_constants.hpp
Labels: 分类:功能需求, 优先级:P2普通, MIP:S5已测试

#567 修正异步查询数据库指令执行过程中 reloadscript 可能会导致崩溃的问题
  src/common/future.cpp
  src/common/future.hpp
  src/map/asyncquery.cpp
  src/map/asyncquery.hpp
  src/map/script.cpp
Labels: 分类:程序缺陷, 优先级:P2普通, MIP:S5已测试

#568 默认禁止在角色、公会、队伍名称中使用单引号 (感谢 "ssboyz" 建议)
  conf/char_athena.conf
Labels: 分类:体验问题, MIP:S6已上线, 优先级:P2普通

#569 调整 mapcache 的依赖设置并更新公用函数的一些实现细节
  rAthena.sln
  src/common/assistant.cpp
  src/common/assistant.hpp
  src/common/processmutex.cpp
  src/common/processmutex.hpp
  src/map/atcommand.cpp
  src/map/map_artisan.cpp
  src/map/map_artisan.hpp
Labels: MIP:S6已上线, 优先级:P2普通

#572 修正 rAthena 在 status_change_start 引入的重算逻辑导致的一系列异常
  src/config/pandas.hpp
  src/map/status.cpp
Labels: 分类:程序缺陷, 优先级:P1较高, MIP:S5已测试

#573 修正编译复兴前版本时的一处编译器警告
  src/map/skill.cpp
Labels: 分类:体验问题, 优先级:P3较低, MIP:S5已测试

#571 汉化部分说明文档, 特别感谢 SSboyz 提供支持
  doc/pandas_atcommands.txt
  doc/pandas_bonus.txt
  doc/pandas_events.txt
  doc/pandas_mapflags.txt
  doc/pandas_script_commands.txt
  tools/python/dist/doc/item_bonus.txt
  tools/python/dist/doc/mapflags.txt
  tools/python/dist/doc/mob_db_mode_list.txt
Labels: 分类:体验问题, 优先级:P2普通, MIP:S5已测试

#575 修正 bonus3 bAddEffOnSkill 中 PC_BONUS_CHK_SC 带入检测参数错误的问题
  src/config/pandas.hpp
  src/map/pc.cpp
Labels: 分类:程序缺陷, MIP:S6已上线, 优先级:P2普通
