Repository PandasWS/Pandas, pull requests merged in 2022-02, with the labels that each got.

#493 更新版本号的呈现样式, 使之能显示专业版的版本号
  conf/msg_conf/map_msg.conf
  conf/msg_conf/map_msg_chs.conf
  conf/msg_conf/map_msg_cht.conf
  conf/msg_conf/translation_cn.yml
  conf/msg_conf/translation_tw.yml
  src/common/assistant.cpp
  src/common/assistant.hpp
  src/common/core.cpp
  src/config/pandas.hpp
  src/map/pc.cpp
  tools/python/dawn_compile.py
  tools/python/dawn_publish.py
  tools/python/imple_versions.py
  tools/python/libs/Common.py
Labels: 分类:功能需求, 优先级:P2普通

#495 实现 getquesttime 脚本指令, 用于查询角色指定任务的时间信息
  doc/pandas_script_commands.txt
  src/config/pandas.hpp
  src/map/script.cpp
Labels: 分类:功能需求, 优先级:P2普通, MIP:S5已测试

#494 更新 KRO 在 2021-05-18 发布的属性相克表 (感谢 "SSBoyz" 提交)
  db/re/attr_fix.yml
Labels: 分类:功能需求, MIP:S6已上线, 优先级:P2普通

#497 清理版本信息处理逻辑并使其输出格式更贴近预期
  .github/workflows/build-and-test.yml
  .github/workflows/codeql-analysis.yml
  src/common/assistant.cpp
Labels: 分类:功能需求, 优先级:P2普通

#496 实现 query_sql_async 和 query_logsql_async 异步数据库查询脚本指令 (感谢 "inhyositsu" 实现)
  doc/pandas_script_commands.txt
  doc/script_commands.txt
  src/common/CMakeLists.txt
  src/common/common.vcxproj
  src/common/common.vcxproj.filters
  src/common/core.cpp
  src/common/future.cpp
  src/common/future.hpp
  src/common/jobqueue.hpp
  src/map/asyncquery.cpp
  src/map/asyncquery.hpp
  src/map/map-server.vcxproj
  src/map/map-server.vcxproj.filters
  src/map/map.cpp
  src/map/script.cpp
  src/map/script.hpp
Labels: 分类:功能需求, MIP:S6已上线, 优先级:P2普通

#500 实现 restore_mes_logic 选项, 用于使新客户端的 mes 指令执行经典换行策略
  .github/workflows/build-and-test.yml
  .github/workflows/codeql-analysis.yml
  conf/battle/pandas.conf
  src/config/pandas.hpp
  src/map/battle.cpp
  src/map/battle.hpp
  src/map/clif.cpp
Labels: 分类:体验问题, 优先级:P2普通, MIP:S5已测试

#502 修正魔物获得异常状态时的伤害数字丢失问题 (感谢 "Sky" 反馈)
  src/map/clif.cpp
Labels: 分类:程序缺陷, 组件:核心, 优先级:P2普通, MIP:S5已测试

#509 实现 itemdb_warning_policy 选项, 用于禁用加载物品数据库时的一些警告信息
  conf/battle/pandas.conf
  conf/msg_conf/translation_cn.yml
  conf/msg_conf/translation_tw.yml
  src/config/pandas.hpp
  src/map/battle.cpp
  src/map/battle.hpp
  src/map/itemdb.cpp
Labels: 分类:体验问题, 优先级:P2普通, MIP:S5已测试

#508 修正生成内存泄露日志文件时程序崩溃的问题
  src/common/utf8.cpp
Labels: 分类:程序缺陷, 优先级:P2普通, MIP:S5已测试

#507 修正部分字段的取值范围限制没被解除的问题
  src/map/pc.cpp
  src/map/script.cpp
Labels: 分类:程序缺陷, MIP:S6已上线, 优先级:P2普通

#518 修正两处近期反馈相对比较集中的地图服务器崩溃
  conf/msg_conf/translation_cn.yml
  conf/msg_conf/translation_tw.yml
  src/config/pandas.hpp
  src/map/map.cpp
  src/map/script.cpp
Labels: 分类:程序缺陷, 优先级:P1较高, MIP:S5已测试

#513 修正背包、仓库、手推车在存储期间发生道具增减会导致道具丢失的问题
  src/common/mmo.hpp
  src/config/pandas.hpp
  src/map/intif.cpp
  src/map/pet.cpp
  src/map/script.cpp
  src/map/storage.cpp
Labels: 分类:程序缺陷, 优先级:P2普通, MIP:S5已测试

#512 实现 unitspecialeffect 脚本指令, 使指定游戏单位可以显示某个特效 [人鱼姬的思念]
  doc/pandas_script_commands.txt
  src/config/pandas.hpp
  src/map/script.cpp
Labels: 分类:功能需求, MIP:S6已上线, 优先级:P2普通

#515 解锁仓库和背包在封包层面的最大容量限制, 使其容量可达到 2000 格
  src/char/int_storage.cpp
  src/char/inter.cpp
  src/common/socket.cpp
  src/config/pandas.hpp
  src/map/chrif.cpp
  src/map/clif.cpp
  src/map/intif.cpp
Labels: 分类:功能需求, MIP:S6已上线, 优先级:P2普通

#517 实现 next_dropitem_special 脚本指令, 用于对下一个掉落到地面上的物品进行特殊设置
  doc/pandas_script_commands.txt
  src/config/pandas.hpp
  src/map/clif.cpp
  src/map/clif.hpp
  src/map/script.cpp
Labels: 分类:功能需求, MIP:S6已上线, 优先级:P2普通

#516 实现 getgradeitem 脚本指令, 用于创造带有指定附魔评级的道具
  doc/pandas_script_commands.txt
  src/config/pandas.hpp
  src/map/script.cpp
Labels: 分类:功能需求, MIP:S6已上线, 优先级:P2普通

#521 实现 bAbsorbDmgMaxHP2 效果调整器, 单次承伤不超过总血量的 n% (感谢 "secretdataz" 实现)
  doc/pandas_bonus.txt
  src/config/pandas.hpp
  src/map/battle.cpp
  src/map/map.hpp
  src/map/pc.cpp
  src/map/pc.hpp
  src/map/script_constants.hpp
Labels: 分类:功能需求, MIP:S6已上线, 优先级:P2普通

#523 实现 bAbsorbDmgMaxHP 的 Bonus2 版本, 单次承伤超过总血量的 n% 时最多只造成总血量 x% 的伤害
  doc/pandas_bonus.txt
  src/config/pandas.hpp
  src/map/battle.cpp
  src/map/map.hpp
  src/map/pc.cpp
  src/map/pc.hpp
  src/map/script.cpp
  src/map/script_constants.hpp
  src/map/skill.cpp
  src/map/skill.hpp
  src/map/status.cpp
Labels: 分类:功能需求, 优先级:P2普通, MIP:S5已测试

#524 实现 mob_default_damagemotion 选项, 用于控制魔物被攻击时受伤动画的默认播放时长
  conf/battle/pandas.conf
  db/item_db.yml
  db/pandas/re/item_db.yml
  src/config/pandas.hpp
  src/map/battle.cpp
  src/map/battle.hpp
  src/map/mob.cpp
Labels: 分类:体验问题, 优先级:P2普通, MIP:S5已测试

#527 修复 getskillinfo 查询技能数据时可能存在错误的问题
  src/map/script.cpp
  src/map/skill.hpp
Labels: 分类:程序缺陷, MIP:S6已上线, 优先级:P2普通
