Repository PandasWS/Pandas, pull requests merged in 2022-08, with the labels that each got.

#619 修正 UTF8-BOM 字符转换成 BIG5 时存在多余反斜杠的问题 (感谢 "DDWT", "jian916" 反馈)
  src/common/assistant.cpp
  src/common/conf.cpp
  src/common/database.cpp
  src/common/utf8.cpp
  src/common/utf8.hpp
  src/common/utf8_defines.hpp
  src/config/pandas.hpp
  src/map/npc.cpp
Labels: 分类:程序缺陷, MIP:S6已上线, 优先级:P2普通

#620 当使用 utf8 / utf8mb4 作为数据库编码时不再给予警告
  conf/msg_conf/translation_cn.yml
  conf/msg_conf/translation_tw.yml
  src/common/sql.cpp
  src/config/pandas.hpp
Labels: 分类:体验问题, MIP:S6已上线, 优先级:P2普通

#625 当 YAML 数据文件中不存在 Body 节点时也依然输出结尾信息
  src/common/database.cpp
  src/config/pandas.hpp
Labels: 分类:体验问题, 优先级:P2普通, MIP:S5已测试

#626 修正拥有 BSF_REM_ON_LOGOUT 标记位的 bonus_script 极少数情况下会在重登后生效的问题 [感谢 "香草" 反馈]
  src/config/pandas.hpp
  src/map/chrif.cpp
Labels: 分类:程序缺陷, 优先级:P3较低, MIP:S5已测试

#628 修正 breakpad 在 Ubuntu 22.04 LTS 无法被默认的 gcc-11 顺利编译的问题
  3rdparty/breakpad/src/client/linux/handler/exception_handler.cc
Labels: 分类:程序缺陷, MIP:S6已上线, 优先级:P2普通

#631 修正 sprintf 脚本指令无法格式化 int64 数值的问题
  src/config/pandas.hpp
  src/map/script.cpp
Labels: 分类:程序缺陷, 优先级:P2普通, MIP:S5已测试

#623 完整的支持读取 UTF8 (不含BOM) 编码的脚本和全部配置、数据文件
  3rdparty/uchardet/uchardet.vcxproj
  3rdparty/uchardet/uchardet.vcxproj.filters
  rAthena.sln
  src/char/char-server.vcxproj
  src/common/common-minicore.vcxproj
  src/common/common.vcxproj
  src/common/conf.cpp
  src/common/utf8.cpp
  src/common/utf8.hpp
  src/common/utils.cpp
  src/login/login-server.vcxproj
  src/map/map-server.vcxproj
  src/tool/csv2yaml.vcxproj
  src/tool/mapcache.vcxproj
  src/tool/yaml2sql.vcxproj
  src/tool/yamlupgrade.vcxproj
  src/web/web-server.vcxproj
Labels: 分类:体验问题, 优先级:P2普通, MIP:S5已测试

#632 调整脚本引擎在 add_str 中分配内存的步进空间
  src/config/pandas.hpp
  src/map/script.cpp
Labels: 分类:体验问题, MIP:S6已上线, 优先级:P2普通

#633 修正触发 str_buf 扩容后, 所有 st->funcname 保存的指令名发生错误的情况
  src/config/pandas.hpp
  src/map/script.cpp
Labels: 分类:程序缺陷, MIP:S6已上线, 组件:核心, 优先级:P2普通

#630 实现与 getinventoryinfo 近似的系列指令用于获取仓库、手推车中的物品信息
  conf/msg_conf/translation_cn.yml
  conf/msg_conf/translation_tw.yml
  doc/pandas_script_commands.txt
  src/char/char.cpp
  src/config/pandas.hpp
  src/map/intif.cpp
  src/map/script.cpp
  src/map/script.hpp
  src/map/storage.cpp
Labels: 分类:功能需求, MIP:S6已上线, 优先级:P2普通

#629 修正复兴前的状态数据库丢失了部分字段导致的一系列问题
  db/item_db.yml
  db/pandas/pre-re/status.yml
  db/status.yml
Labels: 分类:程序缺陷, MIP:S6已上线, 组件:数据, 优先级:P2普通

#634 修正使用 getinventorylist 导致地图服务器崩溃的低级错误 (感谢 "香草" 反馈)
  README.md
  conf/msg_conf/translation_cn.yml
  conf/msg_conf/translation_tw.yml
  src/map/script.cpp
Labels: 分类:程序缺陷, 优先级:P1较高, MIP:S6已上线, 组件:核心

#622 使 bonus2 bSkillNoRequire 效果调整器可以移除 AP/APRATE 施放條件
  doc/pandas_bonus.txt
  src/map/skill.cpp
Labels: 分类:功能需求, MIP:S6已上线, 优先级:P2普通
