Repository PandasWS/Pandas, pull requests merged in 2022-07, with the labels that each got.

#610 移除用于优化 YAML 文件读取速度的疾风缓存机制, 已结束历史使命
  3rdparty/boost/bootstrap.bat
  3rdparty/boost/bootstrap.sh
  CMakeLists.txt
  src/common/CMakeLists.txt
  src/common/common-minicore.vcxproj
  src/common/common-minicore.vcxproj.filters
  src/common/common.vcxproj
  src/common/common.vcxproj.filters
  src/common/database.cpp
  src/common/database.hpp
  src/common/serialize.hpp
  src/common/showmsg.cpp
  src/common/showmsg.hpp
  src/config/pandas.hpp
  src/map/itemdb.cpp
  src/map/itemdb.hpp
  src/map/map-server.vcxproj
  src/map/mob.cpp
  src/map/mob.hpp
  src/map/pc.cpp
  src/map/pc.hpp
  src/map/quest.cpp
  src/map/quest.hpp
  src/map/skill.cpp
  src/map/skill.hpp
  src/map/status.hpp
  src/map/unit.hpp
Labels: 分类:体验问题, MIP:S6已上线, 优先级:P2普通

#611 修正在 Linux 非英文环境下编码转换失败的问题
  src/common/database.cpp
  src/common/utf8.cpp
  src/map/npc.cpp
Labels: 分类:程序缺陷, MIP:S6已上线, 优先级:P2普通

#609 修正煉金召喚魔物技能會造成map崩潰的問題
  src/map/status.cpp
Labels: 分类:程序缺陷, MIP:S6已上线, 优先级:P2普通

#612 实现与 getinventorylist 近似的系列指令用于获取仓库、手推车中的物品信息
  conf/msg_conf/translation_cn.yml
  conf/msg_conf/translation_tw.yml
  doc/pandas_script_commands.txt
  src/char/inter.cpp
  src/config/pandas.hpp
  src/map/intif.cpp
  src/map/pc.cpp
  src/map/pc.hpp
  src/map/script.cpp
  src/map/script.hpp
  src/map/script_constants.hpp
  src/map/storage.cpp
Labels: 分类:功能需求, 优先级:P2普通, MIP:S5已测试

#533 实现 OnPCHarmedExpress 实时事件, 当玩家受到伤害并即将进行结算时触发 [人鱼姬的思念]
  doc/pandas_events.txt
  src/config/pandas.hpp
  src/map/battle.cpp
  src/map/npc.cpp
  src/map/npc.hpp
  src/map/script.cpp
  src/map/script.hpp
  src/map/script_constants.hpp
  src/map/skill.cpp
Labels: 分类:功能需求, MIP:S6已上线, 优先级:P2普通

#614 优化加载与解析 YAML 文件时出现的一些报错体验
  conf/msg_conf/translation_cn.yml
  conf/msg_conf/translation_tw.yml
  src/common/database.cpp
  src/config/pandas.hpp
  src/map/skill.cpp
Labels: 分类:程序缺陷, MIP:S6已上线, 优先级:P2普通

#615 修正倉庫存取事件打斷後 Alt + RightClick 快捷鍵失效和手推車物品無法拖曳情況
  src/map/storage.cpp
Labels: 分类:程序缺陷, 优先级:P2普通, MIP:S5已测试

#618 修正 spawn_level[] 字段返回值不符合预期的问题 (感谢 "Oysica" 反馈)
  src/map/script.cpp
Labels: 分类:程序缺陷, 优先级:P2普通, MIP:S5已测试
