Repository PandasWS/Pandas, pull requests merged in 2022-06, with the labels that each got.

#587 更新终端翻译数据库并修正一些注释错误
  conf/msg_conf/translation_cn.yml
  conf/msg_conf/translation_tw.yml
  doc/pandas_script_commands.txt
Labels: 分类:体验问题, 优先级:P3较低, MIP:S6已上线

#593 使 OnMobDropItemExpress 能够返回即将掉落道具的魔物的游戏单位编号
  doc/pandas_events.txt
  src/map/npc.cpp
Labels: 分类:功能需求, 优先级:P2普通, MIP:S5已测试

#596 实现 reloadlaphinedb 管理员指令, 用于重新加载 Laphine 数据库
  conf/atcommands.yml
  conf/msg_conf/map_msg.conf
  conf/msg_conf/map_msg_chs.conf
  conf/msg_conf/map_msg_cht.conf
  doc/pandas_atcommands.txt
  src/config/pandas.hpp
  src/map/atcommand.cpp
Labels: 分类:体验问题, 优先级:P2普通, MIP:S5已测试

#597 实现 reloadbarterdb 管理员指令, 用于重新加载以物易物数据库
  conf/atcommands.yml
  conf/msg_conf/map_msg.conf
  conf/msg_conf/map_msg_chs.conf
  conf/msg_conf/map_msg_cht.conf
  doc/pandas_atcommands.txt
  src/config/pandas.hpp
  src/map/atcommand.cpp
  src/map/npc.cpp
  src/map/npc.hpp
Labels: 分类:体验问题, 优先级:P2普通, MIP:S5已测试

#594 使 OnPCViewEquipFilter 可以知道被查看角色是否允许其他人看他的装备
  doc/pandas_events.txt
  src/map/clif.cpp
Labels: 分类:功能需求, 优先级:P2普通, MIP:S5已测试

#598 实现 getbossinfo 脚本指令, 用于查询可被 BOSS 雷达探测的魔物重生时间等相关信息
  doc/pandas_script_commands.txt
  src/config/pandas.hpp
  src/map/clif.cpp
  src/map/map.cpp
  src/map/map.hpp
  src/map/mercenary.cpp
  src/map/npc.cpp
  src/map/script.cpp
Labels: 分类:功能需求, 优先级:P2普通, MIP:S5已测试

#591 实现 whodropitem 脚本指令, 用于查询指定道具会从哪些魔物身上掉落
  doc/pandas_script_commands.txt
  src/config/pandas.hpp
  src/map/script.cpp
Labels: 分类:功能需求, MIP:S6已上线, 优先级:P2普通

#539 实现 OnPCStorageAddFilter 过滤器事件, 当玩家准备将道具存入仓库时触发过滤器 [香草]
  doc/pandas_events.txt
  src/config/pandas.hpp
  src/map/npc.cpp
  src/map/npc.hpp
  src/map/script.cpp
  src/map/script.hpp
  src/map/script_constants.hpp
  src/map/storage.cpp
Labels: 分类:功能需求, 优先级:P2普通, MIP:S5已测试

#540 实现 OnPCStorageDelFilter 过滤器事件, 当玩家准备将道具取出仓库时触发过滤器 [香草]
  doc/pandas_events.txt
  src/config/pandas.hpp
  src/map/npc.cpp
  src/map/npc.hpp
  src/map/script.cpp
  src/map/script.hpp
  src/map/script_constants.hpp
  src/map/storage.cpp
Labels: 分类:功能需求, MIP:S6已上线, 优先级:P2普通

#603 修正 getmapspawns 和 getmobspawns 的说明错误 (感谢 "DDWT" 指出)
  doc/pandas_script_commands.txt
Labels: 分类:体验问题, MIP:S6已上线, 优先级:P2普通

#606 修正 reloadbarterdb 没有调用父类 clear 导致数据没被重置的问题
  src/map/npc.cpp
Labels: 分类:程序缺陷, MIP:S6已上线, 优先级:P2普通

#605 修正客户端重置快捷键后 WEB 接口服务器没有删除对应记录的问题
  src/web/userconfig_controller.cpp
Labels: 分类:程序缺陷, MIP:S6已上线, 优先级:P2普通
