Repository PandasWS/Pandas, pull requests merged in 2022-09, with the labels that each got.

#637 更新 Github Actions 的持续集成工作镜像 (因为 Ubuntu 18.04 镜像已被停用)
  .github/workflows/build-and-test.yml
Labels: 分类:体验问题, 优先级:P2普通, 组件:工程

#638 跟随 f82af83, 回滚被删多了的数据库编码策略
  src/common/sql.cpp
  src/config/pandas.hpp
Labels: 分类:体验问题, MIP:S4测试中, 优先级:P2普通

#639 发布流程在打包的时候能将简体中文转换成繁体中文
  tools/python/dawn_publish.py
  tools/python/imple_translate.py
Labels: 优先级:P2普通, 组件:工程

#642 修正某些情况下 getstoragelist 会意外打开仓库界面的问题
  src/map/storage.cpp
Labels: 分类:程序缺陷, MIP:S6已上线, 组件:核心, 优先级:P2普通

#641 修正 battleignore 脚本指令工作异常的问题 (感谢 "Sense" 反馈)
  src/map/script.cpp
Labels: 分类:程序缺陷, MIP:S6已上线, 组件:核心, 优先级:P2普通

#643 修正因技能而触发 OnPCHarmedExpress 导致的事件执行错误
  src/map/skill.cpp
Labels: 分类:程序缺陷, MIP:S6已上线, 组件:核心, 优先级:P2普通

#644 使 getstoragelist 系列指令不必非得在无坐标的浮动 NPC 中使用
  src/map/npc.cpp
Labels: 分类:程序缺陷, MIP:S6已上线, 组件:核心, 优先级:P2普通

#648 更新与编译打包流程相关的一系列辅助脚本
  tools/python/.config.env.sample
  tools/python/.secret.env.sample
  tools/python/Pipfile
  tools/python/Pipfile.lock
  tools/python/config.yml
  tools/python/dawn_compile.py
  tools/python/dawn_fmtargs.py
  tools/python/dawn_publish.py
  tools/python/dawn_symstore.py
  tools/python/libs/Common.py
  tools/python/libs/ConfigParser.py
  tools/python/libs/SecretParser.py
  tools/python/libs/__init__.py
Labels: 分类:功能需求, 组件:工程

#645 魔物翻譯檔(參考RO幻想廳)
  tools/python/db/zh-tw/mobname.txt
Labels: 组件:数据, 优先级:P2普通

#544 实现 OnPCCartAddFilter 过滤器事件, 当玩家准备将道具从背包存入手推车时触发 [香草]
  doc/pandas_events.txt
  src/config/pandas.hpp
  src/map/npc.cpp
  src/map/npc.hpp
  src/map/pc.cpp
  src/map/script.cpp
  src/map/script.hpp
  src/map/script_constants.hpp
Labels: 分类:功能需求, MIP:S6已上线, 优先级:P2普通

#545 实现 OnPCCartDelFilter 过滤器事件, 当玩家准备将道具从手推车取回背包时触发 [香草]
  doc/pandas_events.txt
  src/config/pandas.hpp
  src/map/npc.cpp
  src/map/npc.hpp
  src/map/pc.cpp
  src/map/script.cpp
  src/map/script.hpp
  src/map/script_constants.hpp
Labels: 分类:功能需求, 优先级:P2普通, MIP:S5已测试

#651 fix tools/pythons
  tools/python/libs/ConfigParser.py
Labels: 分类:程序缺陷, 组件:工具, 优先级:P2普通
