Repository PandasWS/Pandas, pull requests merged in 2022-04, with the labels that each got.

#563 更新繁体中文的技能名称翻译对照表 (感谢 "SSBoyz" 提交)
  tools/python/db/zh-tw/skillname.txt
Labels: 分类:体验问题, MIP:S6已上线, 优先级:P2普通

#562 修正魔物死亡但客户端没移除魔物单位的一种新情况 (感谢 "Mr.Siu" 提供环境配合验证)
  src/config/pandas.hpp
  src/map/mob.cpp
Labels: 分类:程序缺陷, MIP:S6已上线, 优先级:P2普通

#565 对疾风缓存机制进行重构, 并调整各类声明和定义的位置
  conf/msg_conf/translation_cn.yml
  conf/msg_conf/translation_tw.yml
  src/common/database.cpp
  src/common/database.hpp
  src/common/serialize.hpp
  src/common/translate.hpp
  src/config/pandas.hpp
  src/map/itemdb.cpp
  src/map/itemdb.hpp
  src/map/map-server.vcxproj
  src/map/mob.cpp
  src/map/mob.hpp
  src/map/pc.cpp
  src/map/pc.hpp
  src/map/quest.cpp
  src/map/quest.hpp
  src/map/skill.cpp
  src/map/skill.hpp
Labels: 分类:体验问题, 优先级:P2普通, MIP:S5已测试

#564 修正交叉切换 Debug / Release 方案进行编译时报错的问题
  3rdparty/breakpad/projects/libraries/crash_common.vcxproj
  3rdparty/breakpad/projects/libraries/crash_generation_client.vcxproj
  3rdparty/breakpad/projects/libraries/crash_generation_server.vcxproj
  3rdparty/breakpad/projects/libraries/crash_report_sender.vcxproj
  3rdparty/breakpad/projects/libraries/exception_handler.vcxproj
  3rdparty/cryptopp/cryptlib.vcxproj
  3rdparty/httplib/httplib.vcxproj
  3rdparty/libconfig/libconfig.vcxproj
  3rdparty/rapidyaml/ryml.vcxproj
  3rdparty/yaml-cpp/yaml-cpp.vcxproj
  rAthena.sln
  src/char/char-server.vcxproj
  src/common/common-minicore.vcxproj
  src/common/common.vcxproj
  src/login/login-server.vcxproj
  src/map/map-server.vcxproj
  src/tool/csv2yaml.vcxproj
  src/tool/mapcache.vcxproj
  src/tool/yaml2sql.vcxproj
  src/tool/yamlupgrade.vcxproj
  src/web/web-server.vcxproj
Labels: 分类:体验问题, 优先级:P2普通, MIP:S5已测试

#503 实现用于获取手推车负重信息的 CartWeight 和 MaxCartWeight 脚本常量
  doc/pandas_script_commands.txt
  src/config/pandas.hpp
  src/map/map.hpp
  src/map/pc.cpp
  src/map/script_constants.hpp
Labels: 分类:功能需求, 优先级:P2普通, MIP:S5已测试
